syntax = "proto3";

package xray.app.router.command;
option java_package = "com.xray.app.router.command";
option java_multiple_files = true;

message PrincipleTargetInfo {
  repeated string tag = 1;
}

message OverrideInfo {
  string target = 2;
}

message BalancerMsg {
  OverrideInfo override = 5;
  PrincipleTargetInfo principle_target = 6;
}

message GetBalancerInfoRequest {
  string tag = 1;
}

message GetBalancerInfoResponse {
  BalancerMsg balancer = 1;
}

service RoutingService {
  rpc GetBalancerInfo(GetBalancerInfoRequest) returns (GetBalancerInfoResponse) {}
}
