syntax = "proto3";

// SPDX-License-Identifier: MPL-2.0
// Derived from Xray-core protocol definitions.

package xray.core.app.observatory.command;
option java_package = "com.xray.core.app.observatory.command";
option java_multiple_files = true;

import "app/observatory/config.proto";

message GetOutboundStatusRequest {}

message GetOutboundStatusResponse {
  xray.core.app.observatory.ObservationResult status = 1;
}

service ObservatoryService {
  rpc GetOutboundStatus(GetOutboundStatusRequest) returns (GetOutboundStatusResponse) {}
}
